### PR TITLE
Travis: Export LD_LIBRARY_PATH for libsyntax.so

### PR DESCRIPTION
**Pull request by stasm**

### CODE REVIEW

**Comment by zbraniecki** [comment]
force-installing cargo moves the job time from 3min to 20 min :( I would love us to find a different solution that doesn't require rebuilding travis-cargo on each job.

**Comment by stasm** [comment]
Well, it's better to have jobs that run 20 minutes and complete than to have it fail. It's pretty bad that #34 which doesn't touch any code is red.

**Comment by stasm** [comment]
I would even recommend removing coveralls completely if it makes Travis run tests in a reliable way.

**Comment by zbraniecki** [comment]
Yeah, I agree that it's better to lose coverage than to fight this :(

**Comment by stasm** [comment]
It looks like the reason why it fails is that it can't find `libsyntax.so`. So it might be related to `rustfmt` and not `coveralls`.

**Comment by stasm** [comment]
Yeah, removing `coveralls` completely didn't fix it.

**Comment by stasm** [comment]
Looks like exporting `LD_LIBRARY_PATH` fixed it. Cool.

**Pull request merged**
