### PR TITLE
Use SPDX 2.1 license expression.

### PR DESCRIPTION
**Pull request by waywardmonkeys**
This improves the usage of automated tooling which consumes the license information.

### CODE REVIEW

**Comment by waywardmonkeys** [comment]
@flodolo The docs that show this change being good are at https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

**Comment by waywardmonkeys** [comment]
If you want me to rebase and force push anything to trigger builds against current versions, just let me know. (For this or any of the others.)

**Comment by flodolo** [comment]
I have an open question about this in the Matrix channel: https://chat.mozilla.org/#/room/#fluent:mozilla.org

**Review by alerque — APPROVED** [review]

**Comment by flodolo** [comment]
See also: https://doc.rust-lang.org/cargo/reference/manifest.html#slash

**Review by flodolo — APPROVED** [review]

**Pull request merged**
