### PR TITLE
sync feature for ressource threading

### PR DESCRIPTION
**Pull request by d34db4b3**
Hi,
I think it could be interesting to allow using the [elsa::sync::FrozenMap](https://docs.rs/elsa/latest/elsa/sync/struct.FrozenMap.html) for ressource sharing between threads.

Let me known what you think.

### CODE REVIEW

**Comment by zbraniecki** [comment]
Thank you for the PR!

@Manishearth does that look reasonable to you?

**Comment by Manishearth** [comment]
It's typically not a good idea to swap out major internal implementation details via cargo features in ways that are externally visible or have perf implications, since cargo features are resolved globally.

It would be better to make it possible to use either backend, I think

**Comment by d34db4b3** [comment]
I thought about this and I also think it would be better to be able to use either.
I used the feature to avoid altering the current behavior of the crate.
I can create a new pull request if you have any advise/opinion about how it should be done.

**Comment by zbraniecki** [comment]
Yes please, I agree with Manish. Let's get a `fluent_resmgr::sync::*` equivalents for sync use. You can macro it out to avoid duplications.

**Pull request closed without merging**
