### PR TITLE
fluent-fallback-cache: Fix waiting from multiple tasks.

### PR DESCRIPTION
**Pull request by emilio**
The cache effectively multiplexes a stream, so we can't just rely on the
stream receiving end to wake up all the relevant tasks.

This fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1613705#c56 for
me.

Disclaimer: I'm not the most familiar with async rust, so take with a
grain of salt.

### CODE REVIEW

**Comment by emilio** [comment]
There's a bunch of unsafe in this file which could get some comments about why it's sound btw.

**Comment by zbraniecki** [comment]
@djg - can you take a look at if this seems like the right fix for the issue I encountered in https://bugzilla.mozilla.org/show_bug.cgi?id=1613705#c56 ?

**Review by zbraniecki — APPROVED** [review]
r+ from Nika as well!

**Comment by zbraniecki** [comment]
Thank you @emilio!

**Pull request merged**
